---
name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  print_infos:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - name: Print OS name
        run: echo "OS is ${{ runner.os }}"
      - name: Print hostname
        run: hostname
      - name: Print current user
        run: whoami
      - name: Check pre-installed tools
        run: |
          if [ ${{ runner.os }} == "Linux" ]; then
            echo "Docker version $(docker --version)"
            echo "Python version $(python --version)"
            echo "Node version $(node --version)"
            echo "Git version $(git --version)"
          fi
