---
name: Hello Workflow

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print hello
        run: echo "Hello from GitHub Actions!"

      - name: Print current date & time
        run: date

      - name: Print the name of triggering branch
        run: echo "Triggered by branch ${{ github.ref_name }}"

      - name: List the files
        run: ls -la

      - name: Print runner's OS
        run: echo "Runner's OS $RUNNER_OS"
